# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:3330/
Accept: application/json

###

POST http://localhost:3330/
Content-Type: application/json

{"score" : 9090}


###

POST http://localhost:3330/user
Content-Type: application/json

{"username": "Nicolas", "password" : "Salocin" }


###

POST http://localhost:3330/level
Content-Type: application/json

{"levelName" : "Ta Mere"}

###

POST http://localhost:3330/result
Content-Type: application/json

{"timeInSeconds" : 1234567890, "nbDeaths" : 1234567890, "scoreValue" : 1234567890, "levelId" : 1234567890, "username" :"Nicolas", "password":"Saaaaalocin"}


###

POST http://localhost:3330/resultFromUserIdAndLevelId
Content-Type: application/json

{"userId" : 1, "levelId" : 1}

###